<?php

namespace Ew;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 19:03:03.
 */
class BusinessExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BusinessException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BusinessException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
