<?php

namespace Ew;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 19:03:07.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ew\Error::handler
     * @todo   Implement testHandler().
     */
    public function testHandler() {
       try{
           Error::handler(new Exception("test"));
           $this->assertEmpty(1, "Não emitiu a exceção");
       } catch (Exception $ex) {
           $this->assertEquals("test", $ex->getMessage(), "Exceção foi modificada");
           $ex->render();
       }
        
        
    }

    /**
     * @covers Ew\Error::critical
     * @todo   Implement testCritical().
     */
    public function testCritical() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ew\Error::toCritical
     * @todo   Implement testToCritical().
     */
    public function testToCritical() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ew\Error::toClient
     * @todo   Implement testToClient().
     */
    public function testToClient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ew\Error::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
