<?php

namespace Ew\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-09 at 19:03:01.
 */
class CommandAbstractTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CommandAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CommandAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ew\Command\CommandAbstract::insertCommandsToClient
     * @todo   Implement testInsertCommandsToClient().
     */
    public function testInsertCommandsToClient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
